### ISSUE TITLE
Background Commands on macOS

### ISSUE THREAD

**Issue by zecanard** [rvmey/TRIGGERcmd-Agent#3]
I’m not sure if your GitHub is alive, but I noticed that it is possible to change a command from Foreground to Background after the fact in the macOS agent. My understanding is that Background commands should not be allowed at all, but currently, Foreground is only enforced at creation, not during edits (in the GUI anyway—of course it’s always possible to set Background by editing the JSON directly).

**Comment by rvmey** [comment]
Thank you Phong.  You’re right.  I’ll create a new version of the Mac agent that prevents changing commands to background commands via the GUI.  I can see how that would be confusing for Mac users because the Mac agent doesn’t support background commands.

**Comment by zecanard** [comment]
Thank you so much!

**Comment by rvmey** [comment]
@zecanard, I fixed it.  You can download the new version of the Mac agent from the https://www.triggercmd.com site.

**Comment by zecanard** [comment]
Verified, thanks!

**Comment by rvmey** [comment]
Closing this issue.
